from pathlib import Path

from stalker_gamma_linux.mo2 import modlist

_MODLIST = (
    "# This file was automatically generated by Mod Organizer.\n"
    "+Enabled Mod A\n"
    "-Disabled Mod B\n"
    "+Enabled Mod C\n"
    "-Graphics_separator\n"
    "*Unmanaged ESP\n"
    "\n"
)


def test_parse_modlist_classifies_enabled_and_disabled() -> None:
    entries = modlist.parse_modlist(_MODLIST)
    names = {entry.name: entry.enabled for entry in entries}

    assert names == {
        "Enabled Mod A": True,
        "Disabled Mod B": False,
        "Enabled Mod C": True,
        "Unmanaged ESP": True,  # `*` = non géré, considéré actif
    }


def test_parse_modlist_skips_comments_separators_and_blanks() -> None:
    entries = modlist.parse_modlist(_MODLIST)
    names = [entry.name for entry in entries]

    assert "Graphics" not in names
    assert not any(name.endswith("_separator") for name in names)
    assert len(entries) == 4


def test_enabled_mods_returns_only_active_names() -> None:
    entries = modlist.parse_modlist(_MODLIST)

    assert modlist.enabled_mods(entries) == ("Enabled Mod A", "Enabled Mod C", "Unmanaged ESP")


def test_read_modlist_missing_file_returns_empty(tmp_path: Path) -> None:
    assert modlist.read_modlist(tmp_path / "profiles" / "G.A.M.M.A") == ()


def test_read_modlist_reads_profile_file(tmp_path: Path) -> None:
    profile = tmp_path / "profiles" / "G.A.M.M.A"
    profile.mkdir(parents=True)
    (profile / "modlist.txt").write_text(_MODLIST, encoding="utf-8")

    entries = modlist.read_modlist(profile)

    assert len(modlist.enabled_mods(entries)) == 3
