"""Chiffres des tuiles de l'accueil (`gui.stats`) — sans GTK."""

from __future__ import annotations

from pathlib import Path

from stalker_gamma_linux.gui import stats
from stalker_gamma_linux.gui.format import UNKNOWN


def _mods_dir(root: Path) -> Path:
    mods = root / "gamma" / "mods"
    mods.mkdir(parents=True)
    return mods


def _write_modlist(root: Path, *lines: str) -> None:
    profile = root / "gamma" / "profiles" / "G.A.M.M.A"
    profile.mkdir(parents=True, exist_ok=True)
    (profile / "modlist.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")


class TestCountMods:
    def test_compte_les_dossiers_de_mods(self, tmp_path: Path) -> None:
        mods = _mods_dir(tmp_path)
        for name in ("100- Base", "200- Weapons", "300- Graphics"):
            (mods / name).mkdir()

        assert stats.count_mods(tmp_path) == 3

    def test_exclut_les_separateurs(self, tmp_path: Path) -> None:
        """Un séparateur est un dossier, pas un mod : il ne peut jamais être « actif »."""
        mods = _mods_dir(tmp_path)
        for name in ("100- Base", "200- Weapons", "Gameplay_separator"):
            (mods / name).mkdir()

        assert stats.count_mods(tmp_path) == 2

    def test_ignore_les_fichiers_poses_a_cote_des_mods(self, tmp_path: Path) -> None:
        """MO2 laisse des fichiers à la racine de `mods/` : ce ne sont pas des mods."""
        mods = _mods_dir(tmp_path)
        (mods / "100- Base").mkdir()
        (mods / "meta.ini").write_text("", encoding="utf-8")

        assert stats.count_mods(tmp_path) == 1

    def test_dossier_absent_rend_inconnu_et_pas_zero(self, tmp_path: Path) -> None:
        """« 0 mod » et « je ne sais pas » ne disent pas la même chose à l'écran."""
        assert stats.count_mods(tmp_path / "rien") is None

    def test_install_vide_rend_bien_zero(self, tmp_path: Path) -> None:
        _mods_dir(tmp_path)

        assert stats.count_mods(tmp_path) == 0


class TestCountActiveMods:
    def test_compte_les_mods_actifs_hors_separateurs(self, tmp_path: Path) -> None:
        _write_modlist(
            tmp_path,
            "# This file was automatically generated by Mod Organizer.",
            "+100- Base",
            "-200- Weapons",
            "+Gameplay_separator",
        )

        assert stats.count_active_mods(tmp_path) == 1

    def test_modlist_absent_rend_inconnu(self, tmp_path: Path) -> None:
        """Install posée mais profil pas encore écrit : « — », pas « 0 »."""
        _mods_dir(tmp_path)

        assert stats.count_active_mods(tmp_path) is None

    def test_modlist_vide_rend_bien_zero(self, tmp_path: Path) -> None:
        """Zéro mod activé est un vrai symptôme : MO2 n'a rien à charger."""
        _write_modlist(tmp_path, "# This file was automatically generated by Mod Organizer.")

        assert stats.count_active_mods(tmp_path) == 0


class TestInstallStats:
    def test_libelle_est_une_fraction_actifs_sur_installes(self) -> None:
        stat = stats.InstallStats(mod_count=728, active_mod_count=579, version="0.6.0")

        assert stat.mods_label == "579 / 728"

    def test_libelle_sans_modlist_montre_le_seul_nombre_connu(self) -> None:
        stat = stats.InstallStats(mod_count=728, active_mod_count=None, version="0.6.0")

        assert stat.mods_label == "728"

    def test_libelle_des_mods_inconnus(self) -> None:
        stat = stats.InstallStats(mod_count=None, active_mod_count=None, version="0.6.0")

        assert stat.mods_label == UNKNOWN


class TestCollect:
    def test_une_seule_passe_pour_toutes_les_valeurs(self, tmp_path: Path) -> None:
        mods = _mods_dir(tmp_path)
        for name in ("100- Base", "200- Weapons"):
            (mods / name).mkdir()
        _write_modlist(tmp_path, "+100- Base", "-200- Weapons")

        collected = stats.collect(tmp_path)

        assert collected.mod_count == 2
        assert collected.active_mod_count == 1
        assert collected.mods_label == "1 / 2"
        assert collected.version  # jamais vide : la version ou le marqueur d'inconnu
