"""Fusion à trois voies de `modlist.txt` — voir tasks/T17-sauvegarde-restauration-modlist.md.

Un test par règle du point 9 du prompt, plus la modlist vide et les fins de
ligne CRLF (l'instance MO2 vient de Windows). Tout est pur : trois chaînes
entrent, une chaîne sort.
"""

from __future__ import annotations

import pytest

from stalker_gamma_linux.mo2 import modlist_merge


def _list(*lines: str, newline: str = "\n") -> str:
    header = "# This file was automatically generated by Mod Organizer."
    return newline.join([header, *lines]) + newline


def _names(text: str) -> list[str]:
    return [entry.name for entry in modlist_merge.parse(text).entries]


def _markers(text: str) -> dict[str, str]:
    return {entry.name: entry.marker for entry in modlist_merge.parse(text).entries}


class TestParse:
    def test_garde_len_tete_les_entrees_et_les_fins_de_ligne(self) -> None:
        parsed = modlist_merge.parse(_list("+A", "-B", newline="\r\n"))

        assert parsed.header == ("# This file was automatically generated by Mod Organizer.",)
        assert parsed.names == ("A", "B")
        assert parsed.newline == "\r\n"
        assert parsed.trailing_newline is True

    def test_un_fichier_lf_reste_lf(self) -> None:
        assert modlist_merge.parse(_list("+A")).newline == "\n"

    def test_une_ligne_incomprise_apres_les_entrees_est_signalee(self) -> None:
        parsed = modlist_merge.parse("+A\n# note ajoutée à la main\n+B\n")

        assert parsed.stray == ("# note ajoutée à la main",)

    def test_les_lignes_vides_ne_sont_pas_des_anomalies(self) -> None:
        parsed = modlist_merge.parse("+A\n\n+B\n\n")

        assert parsed.stray == ()
        assert parsed.names == ("A", "B")


class TestEtatDesMods:
    """« N mods réactivés/désactivés selon tes réglages » — le cas central."""

    def test_une_desactivation_du_joueur_est_rejouee(self) -> None:
        base = _list("+A", "+B", "+C")
        ours = _list("+A", "-B", "+C")  # le joueur a désactivé B
        theirs = _list("+A", "+B", "+C", "+D")  # l'amont ajoute D

        outcome = modlist_merge.merge_modlists(base, ours, theirs)

        assert outcome.merged
        assert outcome.text is not None
        assert _markers(outcome.text)["B"] == "-"
        assert outcome.deactivated == 1
        assert outcome.reactivated == 0

    def test_une_reactivation_du_joueur_est_rejouee(self) -> None:
        outcome = modlist_merge.merge_modlists(
            _list("+A", "-B"), _list("+A", "+B"), _list("+A", "-B")
        )

        assert outcome.merged
        assert outcome.text is not None
        assert _markers(outcome.text)["B"] == "+"
        assert outcome.reactivated == 1

    def test_un_changement_amont_que_le_joueur_na_pas_touche_est_conserve(self) -> None:
        """Le joueur n'a rien dit sur B : c'est l'amont qui décide."""
        outcome = modlist_merge.merge_modlists(
            _list("+A", "+B"), _list("+A", "+B"), _list("+A", "-B")
        )

        assert outcome.merged
        assert outcome.text is not None
        assert _markers(outcome.text)["B"] == "-"
        assert outcome.deactivated == 0  # rien n'a été rejoué : ce n'est pas son réglage

    def test_le_marqueur_non_gere_nest_pas_transforme_en_active(self) -> None:
        """`*` = mod non géré par MO2 : en faire un `+` changerait le sens de la ligne."""
        outcome = modlist_merge.merge_modlists(
            _list("+A", "+B"), _list("+A", "*B"), _list("+A", "+B")
        )

        assert outcome.merged
        assert outcome.text is not None
        assert _markers(outcome.text)["B"] == "*"


class TestModsRetiresEnAmont:
    def test_un_mod_retire_en_amont_nest_jamais_ressuscite(self) -> None:
        """Son dossier n'existe plus sous `mods/` : MO2 l'afficherait en « missing »."""
        base = _list("+A", "+Retire", "+C")
        ours = _list("+A", "-Retire", "+C")  # le joueur l'avait même désactivé
        theirs = _list("+A", "+C")

        outcome = modlist_merge.merge_modlists(base, ours, theirs)

        assert outcome.merged
        assert outcome.text is not None
        assert "Retire" not in _names(outcome.text)
        assert outcome.removed_upstream == 1

    def test_une_entree_que_le_joueur_avait_retiree_reste_celle_de_lamont(self) -> None:
        """Supprimer une ligne que MO2 rajoutera seul n'est pas une décision de fusion."""
        outcome = modlist_merge.merge_modlists(
            _list("+A", "+B", "+C"), _list("+A", "+C"), _list("+A", "+B", "+C")
        )

        assert outcome.merged
        assert outcome.text is not None
        assert _names(outcome.text) == ["A", "B", "C"]
        assert outcome.kept_upstream_entries == 1


class TestModsAjoutesParLeJoueur:
    def test_un_ajout_est_reinsere_a_sa_position_relative(self) -> None:
        """« Auprès de son voisin conservé le plus proche », pas empilé en fin de liste."""
        base = _list("+A", "+B", "+C", "+D")
        ours = _list("+A", "+B", "+MonMod", "+C", "+D")
        theirs = _list("+A", "+B", "+C", "+D", "+NouveauAmont")

        outcome = modlist_merge.merge_modlists(base, ours, theirs)

        assert outcome.merged
        assert outcome.text is not None
        assert _names(outcome.text) == ["A", "B", "MonMod", "C", "D", "NouveauAmont"]
        assert outcome.reinserted == 1

    def test_un_ajout_dont_le_voisin_a_disparu_remonte_au_suivant(self) -> None:
        base = _list("+A", "+Voisin", "+C")
        ours = _list("+A", "+Voisin", "+MonMod", "+C")
        theirs = _list("+A", "+C")  # l'amont a retiré le voisin d'au-dessus

        outcome = modlist_merge.merge_modlists(base, ours, theirs)

        assert outcome.merged
        assert outcome.text is not None
        assert _names(outcome.text) == ["A", "MonMod", "C"]

    def test_un_groupe_dajouts_garde_son_ordre_interne(self) -> None:
        """Cas réel : une grappe d'ajouts en haut de liste, au-dessus du premier séparateur."""
        base = _list("+Fin_separator", "+A")
        ours = _list("+Un", "+Deux", "+Trois", "+Fin_separator", "+A")
        theirs = _list("+Fin_separator", "+A", "+B")

        outcome = modlist_merge.merge_modlists(base, ours, theirs)

        assert outcome.merged
        assert outcome.text is not None
        assert _names(outcome.text) == ["Un", "Deux", "Trois", "Fin_separator", "A", "B"]
        assert outcome.reinserted == 3


class TestSeparateurs:
    def test_un_separateur_est_fusionne_comme_une_entree(self) -> None:
        base = _list("+Audio_separator", "+A")
        ours = _list("+Audio_separator", "-A")
        theirs = _list("+Audio_separator", "+A", "+Video_separator", "+B")

        outcome = modlist_merge.merge_modlists(base, ours, theirs)

        assert outcome.merged
        assert outcome.text is not None
        assert _names(outcome.text) == ["Audio_separator", "A", "Video_separator", "B"]

    def test_un_separateur_ajoute_par_le_joueur_nest_pas_compte_comme_un_mod(self) -> None:
        base = _list("+A")
        ours = _list("+Mes trucs_separator", "+MonMod", "+A")
        theirs = _list("+A")

        outcome = modlist_merge.merge_modlists(base, ours, theirs)

        assert outcome.merged
        assert outcome.text is not None
        assert "Mes trucs_separator" in _names(outcome.text)
        assert outcome.reinserted == 1  # MonMod seulement

    def test_un_separateur_retire_en_amont_nest_pas_compte_comme_un_mod(self) -> None:
        outcome = modlist_merge.merge_modlists(
            _list("+Vieux_separator", "+A"), _list("+Vieux_separator", "-A"), _list("+A")
        )

        assert outcome.merged
        assert outcome.removed_upstream == 0


class TestEnCasDeDouteOnNeFusionnePas:
    def test_un_meme_mod_deux_fois_fait_renoncer(self) -> None:
        outcome = modlist_merge.merge_modlists(
            _list("+A", "+B"), _list("+A", "+A", "+B"), _list("+A", "+B")
        )

        assert not outcome.merged
        assert outcome.text is None
        assert "twice" in outcome.reason

    def test_une_ligne_incomprise_fait_renoncer(self) -> None:
        ours = "+A\n# note ajoutée à la main\n+B\n"

        outcome = modlist_merge.merge_modlists(_list("+A", "+B"), ours, _list("+A", "+B"))

        assert not outcome.merged
        assert "does not understand" in outcome.reason

    def test_un_reordonnancement_concurrent_garde_lordre_amont(self) -> None:
        """Les deux côtés ont bougé la même région : l'amont gagne, et on le dit."""
        base = _list("+A", "+B", "+C", "+D")
        ours = _list("+A", "+C", "+B", "+D")  # le joueur intervertit B et C
        theirs = _list("+A", "+D", "+C", "+B")  # l'amont réordonne aussi

        outcome = modlist_merge.merge_modlists(base, ours, theirs)

        assert outcome.merged
        assert outcome.text is not None
        assert _names(outcome.text) == ["A", "D", "C", "B"]
        assert outcome.order_merged is False
        assert "kept as upstream wrote it" in outcome.report

    def test_un_reordonnancement_du_joueur_seul_est_conserve(self) -> None:
        """L'amont n'a pas touché cette région : rien n'oblige à jeter le travail du joueur."""
        base = _list("+A", "+B", "+C", "+D")
        ours = _list("+A", "+C", "+B", "+D")
        theirs = _list("+A", "+B", "+C", "+D", "+E")

        outcome = modlist_merge.merge_modlists(base, ours, theirs)

        assert outcome.merged
        assert outcome.text is not None
        assert _names(outcome.text) == ["A", "C", "B", "D", "E"]
        assert outcome.order_merged is True


class TestListesVides:
    def test_une_modlist_vide_cote_joueur_fait_renoncer(self) -> None:
        outcome = modlist_merge.merge_modlists(_list("+A"), _list(), _list("+A", "+B"))

        assert not outcome.merged
        assert "empty" in outcome.reason

    def test_une_modlist_amont_vide_fait_renoncer(self) -> None:
        outcome = modlist_merge.merge_modlists(_list("+A"), _list("+A"), _list())

        assert not outcome.merged
        assert "empty" in outcome.reason

    def test_un_instantane_vide_fait_renoncer(self) -> None:
        outcome = modlist_merge.merge_modlists("", _list("+A"), _list("+A"))

        assert not outcome.merged
        assert "empty" in outcome.reason


class TestFinsDeLigne:
    def test_le_crlf_de_lamont_est_preserve(self) -> None:
        """L'instance MO2 vient de Windows : `modlist.txt` y est en CRLF."""
        base = _list("+A", "+B", newline="\r\n")
        ours = _list("+A", "-B", newline="\r\n")
        theirs = _list("+A", "+B", "+C", newline="\r\n")

        outcome = modlist_merge.merge_modlists(base, ours, theirs)

        assert outcome.merged
        assert outcome.text is not None
        assert "\r\n" in outcome.text
        assert outcome.text.count("\r\n") == len(outcome.text.splitlines())
        assert "\n" not in outcome.text.replace("\r\n", "")

    def test_un_amont_en_lf_reste_en_lf_meme_si_le_joueur_est_en_crlf(self) -> None:
        outcome = modlist_merge.merge_modlists(
            _list("+A", "+B"), _list("+A", "-B", newline="\r\n"), _list("+A", "+B")
        )

        assert outcome.merged
        assert outcome.text is not None
        assert "\r" not in outcome.text

    def test_len_tete_amont_est_conserve(self) -> None:
        outcome = modlist_merge.merge_modlists(_list("+A"), _list("-A"), _list("+A"))

        assert outcome.merged
        assert outcome.text is not None
        assert outcome.text.startswith("# This file was automatically generated")


class TestRapport:
    def test_le_rapport_annonce_les_trois_comptes(self) -> None:
        base = _list("+A", "+B", "+Retire", "+C")
        ours = _list("+A", "-B", "+MonMod", "+Retire", "+C")
        theirs = _list("+A", "+B", "+C")

        outcome = modlist_merge.merge_modlists(base, ours, theirs)

        assert outcome.merged
        assert (outcome.reactivated, outcome.deactivated) == (0, 1)
        assert outcome.reinserted == 1
        assert outcome.removed_upstream == 1
        assert "1 mod(s) re-enabled/disabled" in outcome.report
        assert "1 mod(s) you added put back in place" in outcome.report
        assert "1 entry(ies) removed upstream not restored" in outcome.report

    def test_une_fusion_sans_ecart_ne_change_rien(self) -> None:
        text = _list("+A", "+B")

        outcome = modlist_merge.merge_modlists(text, text, text)

        assert outcome.merged
        assert outcome.text == text
        assert not outcome.changed_anything


@pytest.mark.parametrize("newline", ["\n", "\r\n"])
def test_le_resultat_ne_contient_jamais_de_doublon(newline: str) -> None:
    """Invariant dur : un nom deux fois dans `modlist.txt` est un fichier corrompu."""
    base = _list("+A", "+B", "+C", "+D", "+E", newline=newline)
    ours = _list("+E", "+A", "+MonMod", "+B", "+C", newline=newline)
    theirs = _list("+A", "+C", "+B", "+F", newline=newline)

    outcome = modlist_merge.merge_modlists(base, ours, theirs)

    assert outcome.merged
    assert outcome.text is not None
    names = _names(outcome.text)
    assert len(names) == len(set(names))
    assert set(names) == {"A", "B", "C", "F", "MonMod"}
