"""Couche disque de la fusion : instantané amont, lecture verbatim, écriture atomique.

Le piège que ces tests ferment : `Path.read_text` applique la traduction
universelle des sauts de ligne. Lire le `modlist.txt` CRLF d'une instance MO2
venue de Windows avec elle, puis le réécrire, convertirait tout le fichier en
LF sans que personne l'ait demandé.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from stalker_gamma_linux.backups.paths import upstream_modlist_snapshot
from stalker_gamma_linux.mo2 import modlist_sync
from stalker_gamma_linux.mo2.errors import ModlistSyncError

_CRLF_LIST = "# This file was automatically generated by Mod Organizer.\r\n+A\r\n-B\r\n"


def _write_profile(root: Path, text: str) -> Path:
    path = modlist_sync.modlist_path(root)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        handle.write(text)
    return path


def _read_raw(path: Path) -> str:
    with path.open(encoding="utf-8", newline="") as handle:
        return handle.read()


class TestLectureEcriture:
    def test_le_crlf_survit_a_un_aller_retour(self, tmp_path: Path) -> None:
        path = _write_profile(tmp_path, _CRLF_LIST)

        text = modlist_sync.read_verbatim(path)
        assert text == _CRLF_LIST

        modlist_sync.write_atomic(path, text or "")
        assert _read_raw(path) == _CRLF_LIST

    def test_un_fichier_absent_ne_leve_pas(self, tmp_path: Path) -> None:
        assert modlist_sync.read_verbatim(tmp_path / "nulle-part.txt") is None

    def test_lecriture_ne_laisse_pas_de_fichier_temporaire(self, tmp_path: Path) -> None:
        path = _write_profile(tmp_path, "+A\n")

        modlist_sync.write_atomic(path, "+B\n")

        assert sorted(child.name for child in path.parent.iterdir()) == ["modlist.txt"]

    def test_une_ecriture_impossible_leve_une_erreur_typee(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        path = _write_profile(tmp_path, "+A\n")

        def explode(*_args: object, **_kwargs: object) -> None:
            raise OSError("Read-only file system")

        monkeypatch.setattr(modlist_sync.os, "replace", explode)

        with pytest.raises(ModlistSyncError, match="modlist.txt"):
            modlist_sync.write_atomic(path, "+B\n")
        assert _read_raw(path) == "+A\n"


class TestInstantaneAmont:
    def test_lenregistrement_copie_la_liste_courante(self, tmp_path: Path) -> None:
        _write_profile(tmp_path, _CRLF_LIST)

        recorded = modlist_sync.record_upstream_snapshot(tmp_path)

        assert recorded == upstream_modlist_snapshot(tmp_path)
        assert modlist_sync.read_snapshot(tmp_path) == _CRLF_LIST

    def test_sans_profil_il_ny_a_rien_a_enregistrer(self, tmp_path: Path) -> None:
        assert modlist_sync.record_upstream_snapshot(tmp_path) is None


class TestMergeUpstreamModlist:
    def test_sans_instantane_on_sabstient_et_on_enregistre_pour_la_prochaine_fois(
        self, tmp_path: Path
    ) -> None:
        _write_profile(tmp_path, "+A\n+B\n")

        outcome = modlist_sync.merge_upstream_modlist(tmp_path, "+A\n-B\n")

        assert not outcome.merged
        assert "no upstream snapshot" in outcome.reason
        assert modlist_sync.read_snapshot(tmp_path) == "+A\n+B\n"
        assert _read_raw(modlist_sync.modlist_path(tmp_path)) == "+A\n+B\n"

    def test_avec_instantane_les_ecarts_du_joueur_reviennent(self, tmp_path: Path) -> None:
        modlist_sync.write_snapshot(tmp_path, "+A\n+B\n")
        path = _write_profile(tmp_path, "+A\n+B\n+C\n")  # l'amont vient d'écrire ceci

        outcome = modlist_sync.merge_upstream_modlist(tmp_path, "+A\n-B\n+MonMod\n")

        assert outcome.merged
        assert _read_raw(path) == "+A\n-B\n+MonMod\n+C\n"

    def test_linstantane_suit_lamont_jamais_le_resultat_fusionne(self, tmp_path: Path) -> None:
        """Sinon la fusion suivante prendrait les réglages du joueur pour l'amont."""
        modlist_sync.write_snapshot(tmp_path, "+A\n+B\n")
        _write_profile(tmp_path, "+A\n+B\n+C\n")

        modlist_sync.merge_upstream_modlist(tmp_path, "+A\n-B\n")

        assert modlist_sync.read_snapshot(tmp_path) == "+A\n+B\n+C\n"

    def test_sans_liste_precedente_il_ny_a_rien_a_reporter(self, tmp_path: Path) -> None:
        _write_profile(tmp_path, "+A\n")

        outcome = modlist_sync.merge_upstream_modlist(tmp_path, None)

        assert not outcome.merged
        assert "nothing to carry over" in outcome.reason

    def test_sans_liste_apres_la_mise_a_jour_on_le_dit(self, tmp_path: Path) -> None:
        outcome = modlist_sync.merge_upstream_modlist(tmp_path, "+A\n")

        assert not outcome.merged
        assert "no mod list at" in outcome.reason

    def test_le_fichier_nest_pas_reecrit_quand_la_fusion_ne_change_rien(
        self, tmp_path: Path
    ) -> None:
        modlist_sync.write_snapshot(tmp_path, "+A\n+B\n")
        path = _write_profile(tmp_path, "+A\n+B\n")
        before = path.stat().st_mtime_ns

        outcome = modlist_sync.merge_upstream_modlist(tmp_path, "+A\n+B\n")

        assert outcome.merged
        assert path.stat().st_mtime_ns == before
